sudo: required
language: rust
dist: trusty

before_install:
  - cargo clean
  - make -C darknet-sys
  - sudo cp darknet-sys/libdarknet.a /usr/lib

script:
  - cargo build --features gen
  # - cargo fmt -- --write-mode=diff;
  - cargo doc --no-deps

notifications:
  email:
    on_success: never

cache:
  cargo: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
